# Generated by Django 4.2.7 on 2023-11-23 17:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_code', models.AutoField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(default='Startup', max_length=50, verbose_name='Name Of Event')),
                ('image', models.ImageField(upload_to='%Y/%m/%d', verbose_name='Image')),
                ('namber_user', models.IntegerField(default=50, verbose_name='Number Of User')),
                ('ditils', models.TextField(default='Welcome to my event, here I will write all details of the event', verbose_name='Details Of Event')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Time Of Event')),
            ],
            options={
                'ordering': ['-event_code'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
                ('age', models.IntegerField(default=20)),
                ('phone_number', models.CharField(default='078144', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('city', models.CharField(default='Daghdad', max_length=100)),
                ('university', models.CharField(default='Daghded University', max_length=100)),
                ('study_section', models.CharField(default='Computer Engineer', max_length=100)),
                ('knew_event', models.CharField(choices=[('From Friend', 'From Friend'), ('From Social Media', 'From Social Media'), ('Other', 'Other')], default='From Friend', max_length=30)),
                ('artving_at_time', models.CharField(default='I Can', max_length=30)),
                ('visit_hub200', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=30)),
                ('about_me', models.TextField(default='Example text')),
                ('is_accepted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qrcodeapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='Accepted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('is_accepted', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodeapp.event')),
            ],
        ),
    ]
