# Generated by Django 4.2.7 on 2023-11-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0003_alter_applicant_artving_at_time_alter_applicant_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='artving_at_time',
            field=models.CharField(choices=[('I Can', 'I Can'), ('I Try', 'I Try')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='knew_event',
            field=models.CharField(choices=[('From Friend', 'From Friend'), ('From Social Media', 'From Social Media'), ('Other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='study_section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='university',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='visit_hub200',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30),
        ),
    ]
